---
bugfixes:
  - Changed all references for ansible.tower to ansible.controller
minor_changes:
  - Removed the playbook configs folder, it was previously moved to the .github/playbooks directory
  - Created Readme for playbook in the playbooks directory
major_changes:
  - Created awx and controller playbook that users can invoke for using the collection

...
