---
- hosts: "{{ HOSTS | default('satellite.example.com') }}"
  connection: local
  vars:
    organization: "Default Organization"
    validate_certs: false
  tasks:
  - name: "Get organization_info for org {{ organization }}"
    redhat.satellite.organization_info:
    register: organization_info_result
  - debug:
      var: organization_info_result
